version: '3'

volumes:
  user-db-data:

networks:
  user-network:
    driver: bridge

services:
  user:
    container_name: user-service
    build:
      context: .
    ports:
      - 5556:5556
    volumes:
      - ./app:/app
    depends_on:
      - user_db
    restart: on-failure
    networks:
      - user-network

  user_db:
    container_name: user_db
    image: mysql:5.7
    volumes:
      - user-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=user
    restart: always
    networks:
      - user-network
    ports:
      - "13306:3306"
